### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getWorkingDirectory' of null

### ISSUE THREAD

**Issue by Artemiy02** [91bananas/atom-git-revert#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [atom-git-revert](https://github.com/91bananas/atom-git-revert) package 0.2.4

### Stack Trace

Uncaught TypeError: Cannot read property 'getWorkingDirectory' of null

```
At C:\Users\Артемий\.atom\packages\atom-git-revert\lib\git-revert.js:30

TypeError: Cannot read property 'getWorkingDirectory' of null
    at /packages/atom-git-revert/lib/git-revert.js:30:24
    at /packages/atom-git-revert/node_modules/underscore/underscore.js:227:11
    at Function._.each._.forEach (/packages/atom-git-revert/node_modules/underscore/underscore.js:153:9)
    at Function._.filter._.select (/packages/atom-git-revert/node_modules/underscore/underscore.js:226:7)
    at revert (/packages/atom-git-revert/lib/git-revert.js:29:18)
    at /packages/atom-git-revert/lib/git-revert.js:79:13)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/app.asar/src/atom-environment.js:1168:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:325:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  2x -1:44.1.0 tree-view:duplicate (span.name.icon.php-icon.dark-blue)
     -0:26 core:backspace (input.hidden-input)
 11x -0:25.1.0 intentions:highlight (input.hidden-input)
     -0:24.2.0 core:save (input.hidden-input)
     -0:22.5.0 git-revert:revert (div.line.cursor-line)
```

### Non-Core Packages

```
atom-git-revert 0.2.4 
busy-signal 1.3.0 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.0.17 
git-plus 7.3.3 
highlight-selected 0.12.0 
intentions 1.1.2 
linter 2.1.0 
linter-ui-default 1.1.0 
minimap 4.26.8 
minimap-highlight-selected 4.5.0 
pigments 0.39.0 
```

**Comment by 91bananas** [comment]
This is likely because you have a project folder that is a non-Git repo? I just pushed something that should fix this @Artemiy02 

Thank you for the report!
